/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as ChatNewPlanRouteImport } from './routes/_chat.new-plan'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatNewPlanConfigureRouteImport } from './routes/_chat.new-plan.configure'
import { Route as ChatNewPlanCompareRouteImport } from './routes/_chat.new-plan.compare'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatNewPlanRoute = ChatNewPlanRouteImport.update({
  id: '/new-plan',
  path: '/new-plan',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatNewPlanConfigureRoute = ChatNewPlanConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => ChatNewPlanRoute,
} as any)
const ChatNewPlanCompareRoute = ChatNewPlanCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => ChatNewPlanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/new-plan': typeof ChatNewPlanRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/new-plan/compare': typeof ChatNewPlanCompareRoute
  '/new-plan/configure': typeof ChatNewPlanConfigureRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/new-plan': typeof ChatNewPlanRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/': typeof ChatIndexRoute
  '/new-plan/compare': typeof ChatNewPlanCompareRoute
  '/new-plan/configure': typeof ChatNewPlanConfigureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/new-plan': typeof ChatNewPlanRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/new-plan/compare': typeof ChatNewPlanCompareRoute
  '/_chat/new-plan/configure': typeof ChatNewPlanConfigureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/$threadId'
    | '/new-plan'
    | '/settings/archived'
    | '/settings/general'
    | '/new-plan/compare'
    | '/new-plan/configure'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/$threadId'
    | '/new-plan'
    | '/settings/archived'
    | '/settings/general'
    | '/'
    | '/new-plan/compare'
    | '/new-plan/configure'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/_chat/$threadId'
    | '/_chat/new-plan'
    | '/settings/archived'
    | '/settings/general'
    | '/_chat/'
    | '/_chat/new-plan/compare'
    | '/_chat/new-plan/configure'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/new-plan': {
      id: '/_chat/new-plan'
      path: '/new-plan'
      fullPath: '/new-plan'
      preLoaderRoute: typeof ChatNewPlanRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/new-plan/configure': {
      id: '/_chat/new-plan/configure'
      path: '/configure'
      fullPath: '/new-plan/configure'
      preLoaderRoute: typeof ChatNewPlanConfigureRouteImport
      parentRoute: typeof ChatNewPlanRoute
    }
    '/_chat/new-plan/compare': {
      id: '/_chat/new-plan/compare'
      path: '/compare'
      fullPath: '/new-plan/compare'
      preLoaderRoute: typeof ChatNewPlanCompareRouteImport
      parentRoute: typeof ChatNewPlanRoute
    }
  }
}

interface ChatNewPlanRouteChildren {
  ChatNewPlanCompareRoute: typeof ChatNewPlanCompareRoute
  ChatNewPlanConfigureRoute: typeof ChatNewPlanConfigureRoute
}

const ChatNewPlanRouteChildren: ChatNewPlanRouteChildren = {
  ChatNewPlanCompareRoute: ChatNewPlanCompareRoute,
  ChatNewPlanConfigureRoute: ChatNewPlanConfigureRoute,
}

const ChatNewPlanRouteWithChildren = ChatNewPlanRoute._addFileChildren(
  ChatNewPlanRouteChildren,
)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatNewPlanRoute: typeof ChatNewPlanRouteWithChildren
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatNewPlanRoute: ChatNewPlanRouteWithChildren,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
